# Generated by Django 4.2.6 on 2023-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.IntegerField()),
                ('deposit_type', models.CharField(max_length=30)),
                ('deposit_date', models.DateField()),
                ('deposit_description', models.TextField(max_length=30)),
                ('deposit_day', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'deposit',
            },
        ),
    ]
