# Generated by Django 4.2.6 on 2023-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('annual_income', models.IntegerField()),
                ('opening_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
