# Generated by Django 4.2.6 on 2023-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.IntegerField()),
                ('withdraw_date', models.DateField()),
                ('withdraw_description', models.TextField(max_length=30)),
                ('withdraw_day', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'withdraw',
            },
        ),
    ]
