# Generated by Django 4.2.6 on 2023-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_withdrawmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmodel',
            name='withdraw_day',
            field=models.TextField(max_length=30),
        ),
    ]
