# Generated by Django 4.2.6 on 2023-10-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_withdrawmodel_withdraw_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='withdraw_type',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
